### ISSUE TITLE
TypeError: Path must be a string. Received [ 'src/vue-select.js' ]

### ISSUE THREAD

**Issue by pbelyaev** [Haixing-Hu/vue-select#6]
```
path.js:7
throw new TypeError('Path must be a string. Received ' + inspect(path));
^

TypeError: Path must be a string. Received [ 'src/vue-select.js' ]
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at /Users/.../node_modules/resolve/lib/async.js:151:37
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
```

Using in my component like this:

``` javascript
components: {
    'vue-select': require('vue-select2')
},
```

**Comment by Haixing-Hu** [comment]
The bug has been fixed.
